In [42]:
import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
import pandas as pd
import sklearn as sk
import time
from sklearn.neural_network import MLPClassifier

In [38]:
learning_rate=0.000001

In [76]:
Y_label=np.array([0,1]) #np.array([0,2,0,3,1,5,6,4,2,5]*10)
print (Y_label.shape)
X_training_data=np.array([[0., 0.], [1., 1.]]) #np.random.uniform(1,500,size=(7,100))
c=np.zeros((2,2))
c[np.arange(2),Y_label]=1
#print("test",c)
#print("test",np.transpose(c)[9,:])
c=np.transpose(c)
training_count=X_training_data.shape[1]
#features=X_training_data.shape[0]
print (training_count)


print ('Training data size: ',X_training_data.shape) 
#print ('Describe: ',df.describe())
Features=X_training_data.shape[0]
#dict_layers={1:15,2:12,3:10,4:7}

def sigmoid(x,driv=False):
    if driv:
        return x*(1-x)
    return 1/(1 + np.exp(-x))

def softmax(x):
    t=np.exp(x)
    sum1=np.sum(t,axis=0)
    return t/sum1

def weights(neuron,input_features):
    return (np.random.uniform(3,1,size=(neuron,input_features)))

def hypothesis(weights,input_features):
    return np.dot(weights,input_features)
def loss_function(actual_output,network_output):
    return (np.multiply(actual_output,network_output))


actualop=np.identity(7)

w1=weights(15,Features)
z1=hypothesis(w1,X_training_data)
a1=sigmoid(z1)

w2=weights(12,15)
z2=hypothesis(w2,a1)
a2=sigmoid(z2)

w3=weights(10,12)
z3=hypothesis(w3,a2)
a3=sigmoid(z3)

w4=weights(2,10)
z4=hypothesis(w4,a3)
a4=sigmoid(z4)
#print ("a4 staring:",a4)


#print ("a4:",a4)
print ("(np.dot(dz3,np.transpose(a2)))", np.dot(dz3,np.transpose(a2)).shape)

for i in range(10):
    output=softmax(a4)
    
    loss=loss_function(c,np.log(a4))#need to chnage as need to take log accroding to actualop
    if i%100==0:
        print ("loss:",np.sum(np.abs(loss))/training_count)
    #a=np.log([a4[j,k]  for j in range(7) for k in range(7) if Y_label[j]==k])
   # print ("loss:",loss.shape)
    #print ("a4:",a4.shape)
    da4=loss/a4
    dz4=a4*(1-a4)
    w4=w4-learning_rate*(np.dot(dz4,np.transpose(a3)))

    da3=np.dot(np.transpose(w4),(a4*(1-a4)))
    dz3=a3*(1-a3)
    w3=w3-learning_rate*(np.dot(dz3,np.transpose(a2)))

    da2=np.dot(np.transpose(w3),(a3*(1-a3)))
    dz2=a2*(1-a2)
    w2=w2-learning_rate*(np.dot(dz2,np.transpose(a1)))


    da1=np.dot(np.transpose(w2),(a2*(1-a2)))
    dz1=a1*(1-a1)
    w1=w1-learning_rate*(np.dot(dz1,np.transpose(X_training_data)))
    
    z1=hypothesis(w1,X_training_data)
    a1=sigmoid(z1)
    
    z2=hypothesis(w2,a1)
    a2=sigmoid(z2)
    
    z3=hypothesis(w3,a2)
    a3=sigmoid(z3)
    
    z4=hypothesis(w4,a3)
    a4=sigmoid(z4)
    
    
a=np.array([1,-2])

z1=hypothesis(w1,a)
a1=sigmoid(z1)


z2=hypothesis(w2,a1)
a2=sigmoid(z2)


z3=hypothesis(w3,a2)
a3=sigmoid(z3)

z4=hypothesis(w4,a3)
a4=sigmoid(z4)
print ("a4 staring:",softmax(a4))

X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=.0001,hidden_layer_sizes=(15,12,10,7), random_state=1,max_iter=1000)
clf.fit(X_training_data, Y_label)
clf.predict([1,-2])



(2,)
2
Training data size:  (2, 2)
(np.dot(dz3,np.transpose(a2))) (10, 12)
loss: 7.97433725355e-09
a4 staring: [ 0.5  0.5]


C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [33]:
loss[:,:3]

array([[-1.18202126, -0.        , -1.18202126],
       [-0.        , -0.        , -0.        ],
       [-0.        , -1.15202559, -0.        ],
       [-0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.        ]])

In [14]:
loss[:,0]

array([-0.01532759, -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ])